#!/usr/bin/env bash
#
# Regenerates Configurations/BuildNumber.xcconfig, setting CURRENT_PROJECT_VERSION to the
# git commit count. Both targets' Info.plists read CFBundleVersion from that setting, so
# this is what App Store Connect sees as the build number.
#
# Why an xcconfig instead of a build phase: a Run Script phase that rewrites the built
# Info.plist loses the race. Xcode runs ProcessInfoPlistFile *after* the script phases and
# regenerates the plist from CURRENT_PROJECT_VERSION, discarding whatever the script wrote.
# Feeding the number in as a build setting is the one place it survives to the final bundle.
#
# Run this before archiving. The file is gitignored — it is a build input derived from the
# repo, not source. Xcode reads xcconfigs when the project loads, so if Xcode is already
# open, close and reopen the project (or re-run `xcodegen generate`) after this.
#
set -euo pipefail

cd "$(dirname "$0")/.."

if ! n=$(git rev-list --count HEAD 2>/dev/null); then
  echo "error: not a git repository (or no commits) — cannot derive a build number" >&2
  exit 1
fi

out="Configurations/BuildNumber.xcconfig"

cat > "$out" <<EOF
// Generated by scripts/set-build-number.sh — do not edit by hand, do not commit.
// Build number = git commit count: monotonically increasing and unique per commit.
CURRENT_PROJECT_VERSION = $n
EOF

echo "$out -> CURRENT_PROJECT_VERSION = $n"
